spring.application.name=SaveEatBack
spring.data.mongodb.uri=mongodb+srv://bmdev:Bmbaye-2400@cluster0.nqg9mdb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=saveeat_db
server.port=8080