spring.application.name=SaveEatBack
spring.data.mongodb.uri=mongodb+srv://bmdev:Bmbaye-2400@cluster0.nqg9mdb.mongodb.net/saveeat_db?retryWrites=true&w=majority&tls=true&tlsAllowInvalidCertificates=false
spring.data.mongodb.database=saveeat_db
jwt.secret=bmdevsecret

server.port=8080
jwt.expirationMs=86400000

spring.application.version= v1.0.0

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

cloudinary.cloud_name=dgbz1s1wj
cloudinary.api_key=485576976798289
cloudinary.api_secret=TbyR8lTMgtUXmZ782RZ7oPVbN5g
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB