spring.application.name=SaveEatBack
spring.data.mongodb.uri=mongodb+srv://bmdev:Bmbaye-2400@cluster0.nqg9mdb.mongodb.net/saveeat_db?retryWrites=true&w=majority&tls=true&tlsAllowInvalidCertificates=false
spring.data.mongodb.database=saveeat_db
jwt.secret=bmdevsecret

server.port=8080
jwt.expirationMs=86400000

spring.application.version= v1.0.0
